version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: eklo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: azerty
    ports:
      - "27017:27017"
    networks:
      - eklo

networks:
  eklo:
    driver: bridge
