import type { Metadata } from "next";
import "./globals.css";
import { HeaderBar } from "eklo-ui";
import logo from "../assets/logo-eklo.svg";
import { navItems } from "../config";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeaderBar brandLogo={logo.src} navItems={navItems} sticky />
        <div>{children}</div>
      </body>
    </html>
  );
}
